{%- if values.componentName %}
  {%- set name = values.componentName %}
{%- else %}
  {%- set name = values.repoName %}
{% endif -%}
name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Generate Time-Based Tag
      id: generate-tag
      run: |
        TAG=$(date +"%Y%m%d-%H%M%S")
        echo "::set-output name=tag::$TAG"
          
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: registry.nationtech.io
        username: {% raw %}${{ secrets.NATIONTECH_REGISTRY_USER }}{% endraw %}
        password: {% raw %}${{ secrets.NATIONTECH_REGISTRY_PASSWORD }}{% endraw %}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: registry.nationtech.io/${{ name }}:{% raw %}${{ steps.generate-tag.outputs.tag }}{% endraw %}
    
    - name: Update Helm Chart Values
      run: |
        sed -i "s/tag: .*/tag: {% raw %}${{ steps.generate-tag.outputs.tag }}/" ./helm/go-sreez-sample/values.yaml{% endraw %}
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git diff
        git add ./helm/go-sreez-sample/values.yaml
        git commit -m "Upgraded deployment to {% raw %}${{ steps.generate-tag.outputs.tag }}"{% endraw %}

    - name: Update Production Helm Chart Values
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: |
        sed -i "s/tag: .*/tag: {% raw %}${{ github.ref_name }}/" ./helm/go-sreez-sample/values-production.yaml{% endraw %}
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git diff
        git add ./helm/go-sreez-sample/values.yaml
        git commit -m "Upgraded production deployment to {% raw %}${{ github.ref_name }}"{% endraw %}

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
        branch: {% raw %}${{ github.ref }}{% endraw %}
